// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare;
module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/Bottom.vue')['default'];
    Left: typeof import('./src/components/Left.vue')['default'];
    Right: typeof import('./src/components/Right.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Sample: typeof import('./src/components/Sample.vue')['default'];
    SceneViewer: typeof import('./src/components/SceneViewer.vue')['default'];
    Top: typeof import('./src/components/Top.vue')['default'];
  }
}
